import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex justify-between items-center bg-slate-800 py-10">
          <nav className="container">
            <ul className="flex gap-6 text-sm font-medium uppercase tracking-wider text-gray-300">
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/Setup-Cordinates">Cordinates</Link>
              </li>
              <li>
                <Link href="/Setup-Components">Components</Link>
              </li>
              <li>
                <Link href="/Setup-Facilities">Facilities</Link>
              </li>
              <li>
                <Link href="/Map">Map</Link>
              </li>
            </ul>
          </nav>
        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}
